// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqq8fXxVnWAPRVII_BvtzyhFqNPexGu9k',
    appId: '1:833881960618:web:d440e8a60ad6b3ed27a0d3',
    messagingSenderId: '833881960618',
    projectId: 'canastaagro',
    authDomain: 'canastaagro.firebaseapp.com',
    storageBucket: 'canastaagro.appspot.com',
    measurementId: 'G-K4MXEYK3VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8-ZcszcOHxeZB2Y5w2or5sx5KSVFQyBk',
    appId: '1:833881960618:android:cc09568bfc18008a27a0d3',
    messagingSenderId: '833881960618',
    projectId: 'canastaagro',
    storageBucket: 'canastaagro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwKt2lxcTBS2WfMHgflGYYYc7LJnE-L4Y',
    appId: '1:833881960618:ios:51828b78724a90c527a0d3',
    messagingSenderId: '833881960618',
    projectId: 'canastaagro',
    storageBucket: 'canastaagro.appspot.com',
    iosBundleId: 'com.example.canastaAgro',
  );
}
